# Generated by Django 5.1 on 2024-09-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('filiere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=125)),
                ('prenom', models.CharField(max_length=125)),
                ('specialite', models.CharField(max_length=125)),
                ('classes', models.ManyToManyField(to='classes.classes')),
                ('filiere', models.ManyToManyField(to='filiere.filiere')),
            ],
        ),
    ]
