# Generated by Django 5.1.1 on 2024-09-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('filiere', '0001_initial'),
        ('professeur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='classes',
            field=models.ManyToManyField(related_name='professeur', to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='filiere',
            field=models.ManyToManyField(related_name='professeur', to='filiere.filiere'),
        ),
    ]
